name: update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v5
      - name: Update README.md
        run: node index.js > README.md
      - name: Commit change & Push
        run: git config user.name 'github-actions[bot]'
      - name: git - add username
        run: git config user.name 'github-actions[bot]'
      - name: git - add email
        run: git config user.email '51898782+github-actions[bot]@users.noreply.github.com'
      - name: git - add files
        run: git add .
      - name: git - commit files
        run: git commit -am "chore(readme) update profile readme"
      - name: git - push files
        run: git push
